### ISSUE TITLE
Issue posting to web service

### ISSUE THREAD

**Issue by craig8** [Platypi/platypusts#56]
i am having difficulty getting parameters to my web service. I have attempted to isolate the issue through the Json http module, but have not been able to verify that the request is being sent properly.

Note this is a simple auth request with username and password as plat-input elements.  I'm not used to there not being a form around these at this point!

Does the server side matter?  I am using a jaxrs based system on tomcat?

Thanks

Craig

**Comment by wjohnsto** [comment]
Let me make sure I understand the question, you are trying to get information from a plat-input and post it to your server?

If this is the case, what you want to do is take advantage of [plat-bind](https://platypi.io/docs/guide/plat-bind) on the `plat-input` elements to bind the username/password to your context. Then use the [http](https://platypi.io/docs/guide/plat.async.Http) service to send a post request. It would look something like the following:

```
http.json({
        url: // your server url
        method: 'POST',
        data: // your username/password post data
});
```
