### ISSUE TITLE
State of JS

### ISSUE THREAD

**Issue by jonathanamccann** [Platypi/platypusts#65]
https://2020.stateofjs.com/en-US/technologies/#arrows_overview

Framework not listed on 2020 state of JS, please advise.

**Comment by jonathanamccann** [comment]
@wjohnsto @m-s-morgan @matt-landers y'all still shippin it out there?!

What's new, anyone still frequent BHM?

**Comment by matt-landers** [comment]
Lmao! We're out here doing things. I think @m-s-morgan occasionally does some things to the framework, but it needs an overhaul to stay relevant.

**Comment by m-s-morgan** [comment]
I still use it for everything I write
